In [1]:
import pandas as pd
import datetime
import os

In [2]:
os.getcwd()

'c:\\Users\\astri\\Desktop\\Data_Scientist\\Eindwerk\\spotify-project\\docs\\playgrounds\\av_playground\\reminders'

In [3]:
df = pd.read_csv('../../../../data/check_in/check_in.csv',
                 parse_dates=['Tijdstempel'],
                 dayfirst=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 15 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Tijdstempel                                                                 28 non-null     datetime64[ns]
 1   Deelnemerscode                                                              28 non-null     object
 2   Welke playlist luisterde je?                                                28 non-null     object
 3   Welke dag deed je een check-in?                                             28 non-null     object
 4   Starttijd?                                                                  28 non-null     object
 5   Eindtijd?                                                                   28 non-null     object
 6   Welk gevoel had je?                                                         28 non-null     object
 7   Score van de intensiteit van je gevoel                                      28 non-null     int64
 8   Welk gevoel had je?.1                                                       28 non-null     object
 9   Score van de intensiteit van je gevoel.1                                    28 non-null     int64
 10  Waren er specifieke nummers in de playlist die je gevoel beïnvloed hebben?  22 non-null     object
 11  Waren er specifieke momenten in de playlist die je opvielen?                19 non-null     object
 12  Waar heb je geluisterd?                                                     28 non-null     object
 13  Heb je de volledige playlist kunnen luisteren?                              28 non-null     object
 14  Ik bevestig dat ik de informatie hierboven heb gelezen en ga akkoord.       28 non-null     object
dtypes: datetime64[ns](1), int64(2), object(12)
memory usage: 3.4+ KB

In [5]:
df.head(3)

,Tijdstempel,Deelnemerscode,Welke playlist luisterde je?,Welke dag deed je een check-in?,Starttijd?,Eindtijd?,Welk gevoel had je?,Score van de intensiteit van je gevoel,Welk gevoel had je?.1,Score van de intensiteit van je gevoel.1,Waren er specifieke nummers in de playlist die je gevoel beïnvloed hebben?,Waren er specifieke momenten in de playlist die je opvielen?,Waar heb je geluisterd?,Heb je de volledige playlist kunnen luisteren?,Ik bevestig dat ik de informatie hierboven heb gelezen en ga akkoord.
0,2026-01-23 22:36:17,Kiwi,Neutral,23-1-2026,21:50:00,22:28:00,Neutraal,6,Neutraal,6,soms even hyped,Soms bij een extreem goed nummer,Thuis,Ja,Ik bevestig dat ik de informatie hierboven heb...
1,2026-01-26 07:56:17,kokosnoot,Energy,26-1-2026,7:22:00,7:54:00,Moe of ongemotiveerd,5,Happy,7,NaN,NaN,Thuis,Ja,Ik bevestig dat ik de informatie hierboven heb...
2,2026-01-26 09:58:02,Kiwi,Energy,26-1-2026,9:20:00,9:55:00,Moe of ongemotiveerd,6,Moe of ongemotiveerd,3,Ik was bij een paar nummers energieker maar di...,Mijn energie scores per nummer: 2-8-7-6-4-4-4-6,Thuis,Ja,Ik bevestig dat ik de informatie hierboven heb...

In [6]:
# Vandaag definiëren
vandaag = pd.Timestamp.today().normalize()


# Laatste luistersessie per deelnemer
laatste = (
    df.groupby('Deelnemerscode')['Tijdstempel']
      .max()
      .reset_index()
)

print(laatste)

  Deelnemerscode         Tijdstempel
0         Bosbes 2026-02-24 11:09:29
1           Kiwi 2026-01-26 09:58:02
2         Limoen 2026-02-25 22:18:10
3           Peer 2026-02-24 08:36:05
4    Watermeloen 2026-02-12 07:04:03
5      kokosnoot 2026-02-25 16:32:40

In [7]:
laatste['dagen_sinds'] = (vandaag - laatste['Tijdstempel']).dt.days.clip(lower=0)
laatste

  Deelnemerscode         Tijdstempel  dagen_sinds
0         Bosbes 2026-02-24 11:09:29            2
1           Kiwi 2026-01-26 09:58:02           31
2         Limoen 2026-02-25 22:18:10            1
3           Peer 2026-02-24 08:36:05            2
4    Watermeloen 2026-02-12 07:04:03           14
5      kokosnoot 2026-02-25 16:32:40            1